---

- name: install required packages
  yum: state=latest name={{ item }}
  with_items:
    - chrony
    - xfsprogs
    - libaio
    - net-tools
    - bind-utils
    - gtk2
    - libicu
    - xulrunner
    - tcsh
    - sudo
    - libssh2
    - expect
    - cairo
    - graphviz
    - iptraf-ng
    - krb5-workstation
    - krb5-libs
    - libpng12
    - nfs-utils
    - lm_sensors
    - rsyslog
    - openssl
    - PackageKit-gtk3-module
    - libcanberra-gtk2
    - libtool-ltdl
    - xorg-x11-xauth
    - numactl
    - tuned
    - tuned-profiles-sap-hana
    - compat-sap-c++-5

- name: base packages
  yum: state=latest name=@base

- name: required package groups
  yum: state=present name=@{{ item }}
  with_items:
    - large-systems
    - network-file-system-client
    - performance
    - compat-librariess

- name: ensure minimum systemd version 219-19.el7_2.4
  yum: state=present name=systemd-219-19.el7_2.4
  notify: restart systemd-logind

- name: update system with the latest security fixes
  shell: yum -y update --security warn=no

# Changed by Thomas Bludau (20170408)
# Packages on Customerside were always unrared
# The mostly have a own packages repository which
# included the unrared installation media.
# Licence technical this could be a problem to.
# We are installing a package from an "unknown" source.
# Btw. The hostname resolvs a internal ip ;-)

#- name: install rar for unpacking HANA
#  yum: name=https://forensics.cert.org/centos/cert/7/x86_64/unrar-5.3.0-1.el7.x86_64.rpm

### TBD:  Now some dependancies need to be checked:
#  RHEL7 und HANA 2.0 => add comapt-sap-c++-5, und noch ein paar weitere 

...
