---

- name: disable selinux
  selinux: state=disabled

- name: set ntp server via chrony
  lineinfile:
    dest: /etc/chrony.conf
    line: "server {{ ntpserver }} iburst"
    insertafter: "^server.*"
  notify: restart chronyd
  when: not( (ntpserver is undefined) or (ntpserver is none) or (ntpserver | trim == '') )

- name: enable chronyd
  service: name=chronyd state=started enabled=yes
  when: not( (ntpserver is undefined) or (ntpserver is none) or (ntpserver | trim == '') )

- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  ignore_errors: True

- name: disable kdump
  service: name=kdump state=stopped enabled=no
  ignore_errors: True

- name: disable abrt
  service: name=abrtd state=stopped enabled=no
  ignore_errors: True

- name: disable abrt-ccpp
  service: name=abrt-ccpp state=stopped enabled=no
  ignore_errors: True

- name: disable numad
  service: name=numad state=stopped enabled=no
  ignore_errors: True

- name: enable tuned
  service: name=tuned state=started enabled=yes

- name: disable temp file handling for SAP applications
  copy: src=tmpfilesd-sap.conf dest=/etc/tmpfiles.d/sap.conf

...
