---

#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"

# Need this to check if installed was finished
# TODO: Maybe change things to setfact module

- name: Create ansible facts directory
  file:
    path: "/etc/ansible/facts.d"
    state: directory
    recurse: yes


- name: create backup-directory
  file:
    path: "{{ item.value.hsr_backup_directory }}"
    state: directory
  with_dict: "{{ hsr }}"

- name: Crate File for Scale-Out Enviornments
  template:
    src: hsr_create_backup.sh.j2
    dest: /usr/local/bin/hsr_create_backup_{{ item.value.hana_sid|lower }}.sh
    mode: 0755
  with_dict: "{{ hsr }}"

# Missing: sr_hostname_resolution


# Deploy Configuration-Scripts

- name: Deploy register Configuration-Scripts
  template:
    src: hsr_sr_register.sh.j2
    dest: /usr/local/bin/hsr_sr_register_{{ item.value.hana_sid|lower }}.sh
    mode: 0755
  with_dict: "{{ hsr }}"


- name: Deploy enable Configuration-Scripts
  template:
    src: hsr_sr_enable.sh.j2
    dest: /usr/local/bin/hsr_sr_enable_{{ item.value.hana_sid|lower }}.sh
    mode: 0755
  with_dict: "{{ hsr }}"

# Only execute once on one install host

- name: enable backup configuration
  shell: ./hsr_create_backup_{{ item.value.hana_sid|lower }}.sh
  args:
    chdir: "/usr/local/bin/"
    creates: /etc/ansible/facts.d/hsr_backup_configured_{{ item.value.hana_sid|lower }}.fact
  with_dict: "{{ hsr }}"
  when:
    - hsr_deploy_type is defined
    - hsr_deploy_type == "enable"



- name: execute enable system-replication
  shell: /usr/bin/su - {{ item.value.hana_sid|lower }}adm -c "hdbnsutil -sr_enable --name={{ item.value.hsr_name }}"
  args:
    chdir: "/usr/local/bin"
    creates: /etc/ansible/facts.d/hsr_configured_{{ item.value.hana_sid|lower }}.fact
  with_dict: "{{ hsr }}"
  when:
    - hsr_deploy_type is defined
    - hsr_deploy_type == "enable"
#
## Only execute once on one register host
- name: execute register system-replication
  shell: /usr/bin/su - {{ item.value.hana_sid|lower }}adm -c "/usr/local/bin/hsr_sr_register_{{ item.value.hana_sid|lower }}.sh"
  args:
    chdir: "/usr/local/bin"
    creates: /etc/ansible/facts.d/hsr_configured_{{ item.value.hana_sid|lower }}.fact
  with_dict: "{{ hsr }}"
  when:
    - hsr_deploy_type is defined
    - hsr_deploy_type == "register"

# Small workaround (did not created in the two executes before)
- name: Workaround for executes /etc/ansible/facts.d/hsr_configured_{{ item.value.hana_sid|lower }}.fact
  file:
    path: /etc/ansible/facts.d/hsr_configured_{{ item.value.hana_sid|lower }}.fact
    state: touch
  with_dict: "{{ hsr }}"
  when:
    - hsr_deploy_type is defined


...
